name: Production

on:
  push:
    tags: [v*]

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  build:
    needs: 'test'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            NEXT_PUBLIC_SITE_URL=${{ vars.NEXT_PUBLIC_SITE_URL }}
            NEXT_PUBLIC_SITE_NAME=${{ vars.NEXT_PUBLIC_SITE_NAME }}
            NEXT_PUBLIC_STRAPI_API_URL=${{ vars.NEXT_PUBLIC_STRAPI_API_URL }}
            NEXT_PUBLIC_STORAGE_HOST=${{ vars.NEXT_PUBLIC_STORAGE_HOST }}
            NEXT_PUBLIC_CSE_ID=${{ vars.NEXT_PUBLIC_CSE_ID }}
            NEXT_PUBLIC_PAGE_SIZE=${{ vars.NEXT_PUBLIC_PAGE_SIZE }}
            NEXT_PUBLIC_HOME_PAGE_SIZE=${{ vars.NEXT_PUBLIC_HOME_PAGE_SIZE }}
            NEXT_PUBLIC_AVATAR_URL=${{ vars.NEXT_PUBLIC_AVATAR_URL }}
            NEXT_PUBLIC_FAVICON_URL=${{ vars.NEXT_PUBLIC_FAVICON_URL }}
            NEXT_PUBLIC_ICON_URL=${{ vars.NEXT_PUBLIC_ICON_URL }}
            NEXT_PUBLIC_REMARK42_HOST=${{ vars.NEXT_PUBLIC_REMARK42_HOST }}
            NEXT_PUBLIC_REMARK42_SITE_ID=${{ vars.NEXT_PUBLIC_REMARK42_SITE_ID }}
            NEXT_PUBLIC_PLAUSIBLE_DOMAIN=${{ vars.NEXT_PUBLIC_PLAUSIBLE_DOMAIN }}
            NEXT_PUBLIC_PLAUSIBLE_SITE=${{ vars.NEXT_PUBLIC_PLAUSIBLE_SITE }}
            NEXT_PUBLIC_PLAUSIBLE_ENABLED=${{ vars.NEXT_PUBLIC_PLAUSIBLE_ENABLED }}
            STRAPI_API_URL=${{ vars.STRAPI_API_URL }}
            SITEMAP_SIZE=${{ vars.SITEMAP_SIZE }}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{github.repository}}:${{github.ref_name}},ghcr.io/${{github.repository}}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
